In [1]:
import tensorflow as tf

In [4]:
#constants

con1 =  tf.constant(10)
con2 =  tf.constant(3.14566)
con3 =  tf.constant("sparta!!!!!!!!")
con4 =  tf.constant(False)

In [5]:
print([con1,con2,con3,con4])

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=float32, numpy=3.14566>, <tf.Tensor: shape=(), dtype=string, numpy=b'sparta!!!!!!!!'>, <tf.Tensor: shape=(), dtype=bool, numpy=False>]


In [6]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [7]:
import Session as sess

ModuleNotFoundError: No module named 'Session'