In [1]:
import tensorflow as tf
print(tf.__version__)


2.12.0


In [2]:
#constants
con1 = tf.constant(10)
con2 = tf.constant(3.44)
con3 = tf.constant("zeeman")
con4 = tf.constant(False)

In [3]:
print([con1,con2,con3,con4])

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=float32, numpy=3.44>, <tf.Tensor: shape=(), dtype=string, numpy=b'zeeman'>, <tf.Tensor: shape=(), dtype=bool, numpy=False>]


In [4]:
with tf.compat.v1.Session() as sess:
    
  # Build a dataflow graph.
  c = tf.constant(77)
  d = tf.constant(88)
  e = tf.add(c, d)

  # Execute the graph and store the value that `e` represents in `result`.
  result = sess.run(e)
  print(result)

165


In [5]:
with tf.compat.v1.Session() as sess:

    Addition = tf.constant(20) + tf.constant(30)
    Subtraction = tf.constant(25) - tf.constant(13)
    Multiplication = tf.constant(25) * tf.constant(13)

    result = sess.run([Addition,Subtraction,Multiplication])
    print(result)

[50, 12, 325]


In [6]:
with tf.compat.v1.Session() as sess:

    Addition = tf.constant([20,34,45,67]) + tf.constant([30,45,78,98])
    
    result = sess.run([Addition])
    print(result)

[array([ 50,  79, 123, 165])]


In [9]:
with tf.compat.v1.Session() as sess:

    str1 = tf.constant("Behemoth is the king of 5th Hell ") 
    str2 = tf.constant("But Asmodeus subsides him")
    
    result = sess.run(str1+str2)
    print(result)

b'Behemoth is the king of 5th Hell But Asmodeus subsides him'


In [8]:
with tf.compat.v1.Session() as sess:

   a = tf.placeholder(tf.int32)
   b = a*2


   result = sess.run(b,feed_dict={a:5})
   print(result)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
with tf.compat.v1.Session() as sess:

   a = tf.placeholder(tf.float32)
   b = (a/34)*3


   result = sess.run(b,feed_dict={a:34.33})
   print(result)

3.0291178


In [ ]:
with tf.compat.v1.Session() as sess:

   a = tf.placeholder(tf.int32)
   b = a*3


   result = sess.run(b,feed_dict={a:[23,45,67]})
   print(result)

[ 69 135 201]


In [ ]:
with tf.compat.v1.Session() as sess:

   str_1 = tf.placeholder(tf.string)
   str_2 = "I am " + str_1


   result = sess.run(str_2,feed_dict={ str_1 : ["bob","marley","john","ceaser"]})
   print(result)

[b'I am bob' b'I am marley' b'I am john' b'I am ceaser']


In [ ]:
with tf.compat.v1.Session() as sess:

    var1 = tf.Variable([20],tf.int32)
    b = a*3


    result = sess.run(b,feed_dict={a:[23,45,67]})
    print(result)

In [ ]:
init = tf.global_variables_initializer()

In [ ]:
with tf.compat.v1.Session() as sess:

    sess.run(init)
    result = sess.run(var1)
    print(result)

[20]


In [ ]:
with tf.compat.v1.Session() as sess:

   updated_var1 = tf.assign(var1,[25])

   result = sess.run(updated_var1)
   print(result)

[25]


In [ ]:
with tf.compat.v1.Session() as sess:
   
   w = tf.Variable([10],tf.int32)
   b = tf.Variable([5],tf.int32)
   x = tf.placeholder(tf.int32)

  
   init1 = tf.global_variables_initializer()
   sess.run(init1)

   linear_model = w*x + b

   result = sess.run(linear_model,feed_dict={x:[1,2,3]})
   print(result)

[15 25 35]


<img src="https://upload.wikimedia.org/wikipedia/commons/b/b5/Neuron.svg"/>